name: real_estate_blockchain
description: Real Estate trading floor

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.6+9

environment:
  sdk: ">=2.19.0-0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # Injection Dependencies
  injectable:
  get_it:
  # Utils
  flutter_native_splash: ^2.2.18
  flutter_dotenv: ^5.0.2
  freezed_annotation: ^2.1.0
  flutter_bloc: ^8.1.1
  dartz: ^0.10.1
  equatable: ^2.0.3
  json_annotation: ^4.8.0
  file_picker: ^5.2.2
  image_picker: ^0.8.7
  logger: ^1.1.0
  recase: ^4.1.0
  url_launcher: ^6.1.8
  rxdart: ^0.27.7
  permission_handler: ^10.2.0
  flutter_image_compress: ^1.1.3
  flutter_isolate: ^2.0.4
  path_provider: ^2.0.14
  uuid: ^3.0.7
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.0
  flutter_local_notifications: ^13.0.0
  firebase_messaging: ^14.4.1
  firebase_crashlytics: ^3.1.0
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.1.0
  fluttertoast: ^8.2.1
  curl_logger_dio_interceptor: ^1.0.0

  # UI
  photo_view: ^0.14.0
  go_router: ^6.2.0
  loader_overlay: ^2.0.7
  flutter_screenutil: ^5.5.3+2
  flutter_svg: 2.0.2
  flutter_animate: ^4.1.0
  dropdown_button2: ^2.0.0
  smooth_page_indicator: ^1.0.0+2
  get_it_mixin: ^3.1.4
  dotted_border: ^2.0.0+3
  lottie: ^2.2.0
  custom_refresh_indicator: ^2.0.1
  sliver_tools: ^0.2.8
  shimmer: ^2.0.0
  flutter_list_view: ^1.1.21
  carousel_slider: ^4.2.1
  webview_flutter: ^3.0.4
  pin_code_fields: ^7.4.0
  infinite_scroll_pagination: ^3.2.0
  adaptive_dialog: ^1.8.3+1

  dialog_flowtter: ^0.3.3
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.2.3
  jiffy: ^6.2.1
  #grpc
  grpc: ^3.1.0
  protobuf: ^2.1.0
  month_picker_dialog: ^2.0.2
  local_auth: ^2.1.6


  # Language
  intl: ^0.18.0
  intl_utils: ^2.8.2
  flutter_localizations:
    sdk: flutter
  # Service
  dio: ^5.0.1
  pretty_dio_logger: ^1.1.1
  
  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # Map 
  flutter_map:
  latlong2:
  geolocator: ^9.0.2
  async: ^2.10.0
  currency_text_input_formatter: ^2.1.10

  # Websocket
  stomp_dart_client: ^0.4.4
  font_awesome_flutter: ^10.5.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2



dependency_overrides:
  macos_ui:
    git:
      url: https://github.com/Mayb3Nots/macos_ui.git
      ref: dev

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Annotation
  freezed: ^2.1.0+1
  json_serializable:
  # Project
  change_app_package_name:
  # Builder
  injectable_generator:
  build_runner: ^2.3.3
  flutter_gen_runner: 5.2.0
  hive_generator:
  flutter_launcher_icons: ^0.12.0
  rename: ^2.1.1
  another_flushbar: ^1.12.30

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - fonts/
    - assets/
    - assets/images/
    - assets/icons/
    - assets/lotties/
    - assets/locations/
    - envs/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope-ExtraLight.ttf
          weight: 200
        - asset: fonts/Manrope-Light.ttf
          weight: 300
        - asset: fonts/Manrope-Regular.ttf
          weight: 400
        - asset: fonts/Manrope-Medium.ttf
          weight: 500
        - asset: fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: fonts/Manrope-Bold.ttf
          weight: 700
        - asset: fonts/Manrope-ExtraBold.ttf
          weight: 800
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_intl:
  enabled: true
  arb_dir: lib/languages/l10n
  output_dir: lib/languages/generated

flutter_native_splash:
  color: "#111827"


flutter_gen:
  output: lib/assets/

  integrations:
    flutter_svg: true

flutter_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/realust.png"
  min_sdk_android: 21 # android min sdk min:16, default 21